version: '3.3'
services:
  database:
    container_name: database_container
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d

  app:
    image: app:latest
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target/servlet-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
    ports:
      - '8888:8080'
    depends_on:
      - database