version: '3.3'
services:
  database:
    container_name: database_container
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --init-file /docker-entrypoint-initdb.d
    expose:
      - '3306'
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d

  tomcat:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    volumes:
      - ./target/servlet-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
    ports:
      - '8888:8080'
    depends_on:
      - database