version: '2.1'
services:
  database:
    hostname: database
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin -uroot -proot ping
      interval: 10s
      timeout: 20s
      retries: 30

  tomcat:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    volumes:
      - ./target/servlet-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
    ports:
      - '8081:8080'
    environment:
      DB_URL: 'jdbc:mysql://database:3306/db'
      DB_LOGIN: 'user'
      DB_PASSWORD: 'password'
    depends_on:
      database:
        condition: service_healthy
